### ISSUE TITLE
Python Console window: Matplotlib requires colours to use BGR rather than RGB!?

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2334]
I have the following Matplotlib-related command:

```
plt.plot(self.__voi.values(), self.__s.values(), '#0071bd', label=self.__s.name())
plt.plot(self.__voi.values(), self.__i.values(), '#d9521a', label=self.__i.name())
plt.plot(self.__voi.values(), self.__r.values(), '#edb020', label=self.__r.name())
plt.plot(self.__voi.values(), self.__d.values(), '#7e2f8e', label=self.__d.name())
```

Now, if I run that code from the `Python Console` window then I get the following figure:

![Screen Shot 2020-04-26 at 6 18 23 PM](https://user-images.githubusercontent.com/602265/80299670-57998f80-87ea-11ea-886c-0184a56893f9.png)

which doesn't have the colours I would expect. On the other hand, I run that same code from OpenCOR's Python shell then I get the following figure:

![Screen Shot 2020-04-26 at 6 19 20 PM](https://user-images.githubusercontent.com/602265/80299688-75ff8b00-87ea-11ea-8976-604991388104.png)

which does indeed have the colours I would expect. Interestingly enough, if I save the first figure then the resulting image file has the expected colours:

![SIRD_model](https://user-images.githubusercontent.com/602265/80299737-de4e6c80-87ea-11ea-9452-127b45d3be44.png)

FWIW, when run from within the `Python Console` window, the Python script must specify colours using BGR rather than RGB...!?

**Comment by dbrnz** [comment]
Hmm, OpenCOR uses a version of matplotlib's Qt interface that has been patched to work with PythonQt. I wonder what happens when OpenCOR's Python is run in a `qtconsole`? That is, with using:
```
$ ./OpenCOR.app/Contents/Frameworks/Python/bin/runjupyter qtconsole --kernel OpenCOR
```
If RGB works as expected there then the issue is with our patched Qt interface; if `qtconsole` also uses BGR then the issue is a general one with matplotlib's Qt interface.

**Comment by agarny** [comment]
I just tried:
```
$ ./OpenCOR.app/Contents/Frameworks/Python/bin/runjupyter qtconsole --kernel OpenCOR
```
but I am getting this:
```
Traceback (most recent call last):
  File "/Users/Alan/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/bin/../../../../../OpenCOR.app/Contents/Frameworks/Python/bin/jupyter-qtconsole", line 11, in <module>
    load_entry_point('qtconsole==4.5.5', 'gui_scripts', 'jupyter-qtconsole')()
  File "/Users/Alan/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/Alan/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/Alan/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/Alan/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/Alan/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/lib/python3.7/site-packages/qtconsole/qtconsoleapp.py", line 60, in <module>
    from qtconsole.qt import QtCore, QtGui
  File "/Users/Alan/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/lib/python3.7/site-packages/qtconsole/qt.py", line 24, in <module>
    QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
  File "/Users/Alan/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/lib/python3.7/site-packages/qtconsole/qt_loaders.py", line 402, in load_qt
    result = loaders[api]()
  File "/Users/Alan/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/lib/python3.7/site-packages/qtconsole/qt_loaders.py", line 339, in import_pythonqt
    from PythonQt import QtCore, QtSvg, QtGui
ModuleNotFoundError: No module named 'PythonQt'
```
