### ISSUE TITLE
Rely on the developer's Sphinx and its extensions to build the documentation

### ISSUE THREAD

**Issue by agarny** [opencor/opencor#2593]
Our documentation now requires the `sphinx_copybutton` and `sphinx_inline_tabs` Sphinx extensions, so we need to add them to our Python packages.

**Comment by agarny** [comment]
Before adding the `sphinx-copybutton` and `sphinx-inline-tabs` packages to `PythonPackages`, I thought I would try to build `PythonPackages` as-is. However, it (currently?) fails with:
```
Building wheels for collected packages: ipykernel
  Building wheel for ipykernel (pyproject.toml): started
  Building wheel for ipykernel (pyproject.toml): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /Users/Alan/OpenCOR/build/OpenCOR.app/Contents/Frameworks/Python/bin/python3 /Users/Alan/OpenCOR/ext/src/plugins/thirdParty/PythonPackages/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/9z/_ffcsljd3416mxt5jr3cbdzc0000gn/T/tmp9nf2sdg5
       cwd: /private/var/folders/9z/_ffcsljd3416mxt5jr3cbdzc0000gn/T/pip-req-build-kvqc_laf
  Complete output (22 lines):
  Traceback (most recent call last):
    File "/Users/Alan/OpenCOR/ext/src/plugins/thirdParty/PythonPackages/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/Users/Alan/OpenCOR/ext/src/plugins/thirdParty/PythonPackages/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/Alan/OpenCOR/ext/src/plugins/thirdParty/PythonPackages/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
      metadata_directory)
    File "/private/var/folders/9z/_ffcsljd3416mxt5jr3cbdzc0000gn/T/pip-build-env-xsgfckgt/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 222, in build_wheel
      wheel_directory, config_settings)
    File "/private/var/folders/9z/_ffcsljd3416mxt5jr3cbdzc0000gn/T/pip-build-env-xsgfckgt/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/9z/_ffcsljd3416mxt5jr3cbdzc0000gn/T/pip-build-env-xsgfckgt/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 259, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/private/var/folders/9z/_ffcsljd3416mxt5jr3cbdzc0000gn/T/pip-build-env-xsgfckgt/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 115, in <module>
      from ipykernel.kernelspec import write_kernel_spec, make_ipkernel_cmd, KERNEL_NAME
    File "/private/var/folders/9z/_ffcsljd3416mxt5jr3cbdzc0000gn/T/pip-req-build-kvqc_laf/ipykernel/__init__.py", line 2, in <module>
      from .connect import *
    File "/private/var/folders/9z/_ffcsljd3416mxt5jr3cbdzc0000gn/T/pip-req-build-kvqc_laf/ipykernel/connect.py", line 15, in <module>
      from ipython_genutils.path import filefind
  ModuleNotFoundError: No module named 'ipython_genutils'
  ----------------------------------------
  ERROR: Failed building wheel for ipykernel
Failed to build ipykernel
ERROR: Could not build wheels for ipykernel, which is required to install pyproject.toml-based projects
ninja: build stopped: subcommand failed.
```
even though the `ipython-genutils` package is installed. Not sure why this is the case (@dbrnz, any ideas?). Either way, I am not sure it's worth spending too much time trying to understand what is going wrong here. Instead, like for `libOpenCOR`, we should rely on the developer having Python, Sphinx, as well as the `sphinx-copybutton` and `sphinx-inline-tabs` packages. Failing that, we don't build the documentation and disable the `HelpWindow` plugin.

**Comment by agarny** [comment]
Also, to use a more recent version of Sphinx means that we won't have to distinguish between the version of Sphinx shipped with OpenCOR and the latest version of Sphinx (see https://github.com/opencor/sphinx-theme/commit/70c673519064d67e40145e17e062b3ec4537d8a7).

**Comment by dbrnz** [comment]
It looks as if `ipykernel` is now using `pyproject.toml` files for configuration, which has possibly confused something...

But if requiring a developer to have a recent Sphinx installed gets around this then great!

**Comment by agarny** [comment]
> It looks as if `ipykernel` is now using `pyproject.toml` files for configuration, which has possibly confused something...

Ok, probably not worth our time figuring out what's broken then.

> But if requiring a developer to have a recent Sphinx installed gets around this then great!

A recent Sphinx doesn't get around the `ipykernel` problem. Just that we currently need two set of CSS rules for our documentation. Indeed, for libOpenCOR, I use the latest version of Sphinx (since I can't use the version shipped with OpenCOR) and that's how I found out that the version of Sphinx shipped with OpenCOR uses tables when generating HTML code for `.. code-block::` while the latest version of Sphinx doesn't. So, I have to account for both cases. Now that we are only going to use a recent Sphinx, I won't have to worry about the version of Sphinx shipped with OpenCOR.

**Comment by dbrnz** [comment]
So is there an issue with `ipykernel` when building OpenCOR's Python plugins? Or only if `sphinx` is part of the mix??

**Comment by agarny** [comment]
There is indeed an issue with `ipykernel` when trying to build the `PythonPackages` plugin (i.e. by setting `USE_PREBUILT_PYTHON_PACKAGES_PACKAGE` to `OFF`). I don't believe there is an issue with Sphinx at all. It's just that for libOpenCOR and OpenCOR's documentation, I now rely on two Sphinx extensions that are obviously not shipped with OpenCOR, hence I cannot anymore use OpenCOR's Sphinx to build the documentation. I therefore wanted to add those extensions to the `PythonPackages` plugin, but I can't since I can't even build it as it currently stands.
