### ISSUE TITLE
ctypes error when starting opencor

### ISSUE THREAD

**Issue by MichaelClerx** [opencor/opencor#2605]
On Fedora 35, using the latest (2022-01-11) snapshot, I get a Python ctypes error when loading OpenCOR.
It doesn't stop cor from loading, or working, but I assume some of the Python functionality will be gone

```
[michael@fedora OpenCOR-2021-10-05-Linux]$ ./OpenCOR 
Traceback (most recent call last):
  File "", line 11, in <module>
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/qtconsole/inprocess.py", line 5, in <module>
    from ipykernel.inprocess import (
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/ipykernel/connect.py", line 18, in <module>
    import jupyter_client
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/jupyter_client/connect.py", line 24, in <module>
    import zmq
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/zmq/__init__.py", line 50, in <module>
    _load_libzmq()
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/zmq/__init__.py", line 16, in _load_libzmq
    import ctypes
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/numpy/core/__init__.py", line 99, in <module>
    from . import _dtype_ctypes
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/numpy/core/_dtype_ctypes.py", line 25, in <module>
    import _ctypes
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```

**Comment by MichaelClerx** [comment]
An easier way to see it:
```
[michael@fedora OpenCOR-2021-10-05-Linux]$ ./pythonshell
Traceback (most recent call last):
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/numpy/core/__init__.py", line 99, in <module>
    from . import _dtype_ctypes
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/numpy/core/_dtype_ctypes.py", line 25, in <module>
    import _ctypes
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
Python 3.7.5 (default, Dec 11 2020, 14:03:40) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

and then

```
>>> import ctypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
>>> 
```

**Comment by MichaelClerx** [comment]
or even
```
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/numpy/core/__init__.py", line 99, in <module>
    from . import _dtype_ctypes
  File "/home/michael/dev/ext/opencor/OpenCOR-2021-10-05-Linux/python/lib/python3.7/site-packages/numpy/core/_dtype_ctypes.py", line 25, in <module>
    import _ctypes
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```

So perhaps it's because I'm using a numpy that was compiled on another distro?

**Comment by agarny** [comment]
Hmm... interesting point about numpy having been compiled on another distro. @dbrnz, do you think that numpy having been built on Ubuntu could be the reason that it's not working "fine" on Fedora? I certainly remember (several years ago) OpenCOR working fine on Ubuntu, but needing at least one more system library to work on Fedora.

**Comment by dbrnz** [comment]
@agarny this has nothing to do with `numpy` but instead is because `_ctypes.so`, created as part of our Python build, references `libffi.so.7` and Fedora doesn't (I'm guessing it has `libffi.so.6`).

Testing under Rocky Linux 8.5 (which is based on Fedora/RedHat/CentOS) finds:
```
$ ldd python/lib/python3.7/lib-dynload/_ctypes.so
	linux-vdso.so.1 (0x00007ffc34f5c000)
	libffi.so.7 => not found
	libc.so.6 => /lib64/libc.so.6 (0x00007f2df6c44000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2df7009000)

$ ls /usr/lib64/libffi.so.*
/usr/lib64/libffi.so.6  /usr/lib64/libffi.so.6.0.2
```

Rocky Linux 8.5 (and hence RedHat and CentOS) has other issues with OpenCOR, namely:
```
$ ./pythonshell
/home/dave/build/OpenCOR-2021-10-05-Linux/bin/OpenCOR: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/dave/build/OpenCOR-2021-10-05-Linux/bin/../lib/libpython3.7m.so)
/home/dave/build/OpenCOR-2021-10-05-Linux/bin/OpenCOR: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/dave/build/OpenCOR-2021-10-05-Linux/bin/../lib/libGL.so.1)
```
Although we can disregard these at the moment, it also highlights that the set of "standard" libraries in a given Linux release (i.e. Ubuntu 20.04) are not necessarily available in the latest releases of other Linux flavours

**Comment by dbrnz** [comment]
Hmm, [this](https://askubuntu.com/questions/1286772/libffi-so-7-cannot-open-shared-object-file-no-such-file-or-directory) indicates that Ubuntu 20.10 provides `libffi.so.8`, which would mean that OpenCOR Python built under one Ubuntu 20 version wouldn't run out-of-the box on the other...

`ldconfig -p |  grep ffi` though is a handy command to see what versions of `libffi` are available.

**Comment by agarny** [comment]
Yes, Linux distributions are always going to be a nightmare. That's one of the reasons OpenCOR's build system is the way it is, but even with that it can be tedious, as I experienced a few months ago when getting OpenCOR to build on CentOS 7. I guess that's the reason we clearly mention that we support the latest LTS version of Ubuntu...

**Comment by agarny** [comment]
We are working on releasing OpenCOR 0.7 which will be the only official version of OpenCOR with our current Python bindings. From there, we will switch to libOpenCOR for OpenCOR's backend (this will be OpenCOR 0.8), so closing this issue.
