### ISSUE TITLE
Running OpenCOR through Python has a memory leak when you access variables. 

### ISSUE THREAD

**Issue by FinbarArgus** [opencor/opencor#2798]
[OpenCOR_mem_leak.zip](https://github.com/user-attachments/files/16413158/OpenCOR_mem_leak.zip)

Above, I have attached a minimal example of running OpenCOR through python. Memory is printed in the SimulationHelper class.

When we access results with 

`result = sim.simulation.results().states()['heart/q_lv'].values() # if i comment this out there is no memory issue...`

after a simulation, the reset_and_clear doesn't clear all memory use. 

The leak is present in both OpenCOR-0-7-1-Linux and OpenCOR-2022-05-31-Linux

This could potentially be due to here...

https://github.com/opencor/opencor/blob/fcc99737ef15e4eb776662f20f7b467da6fa6e77/src/plugins/support/SimulationSupport/src/simulationsupportpythonwrapper.cpp#L350

not including data()->reset() like here... 

https://github.com/opencor/opencor/blob/fcc99737ef15e4eb776662f20f7b467da6fa6e77/src/plugins/support/SimulationSupport/src/simulationsupportpythonwrapper.cpp#L200C13-L200C14

**Comment by agarny** [comment]
Argh, your Python script uses a module that is only available on UNIX systems but not on macOS though. Thank god for Docker...

**Comment by agarny** [comment]
Well, no `getrusage` method in the `resource` module...?!
```
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "<frozen runpy>", line 286, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/root/Data/Desktop/OpenCOR_mem_leak/run_simple.py", line 15, in <module>
    sim.run()
  File "/root/Data/Desktop/OpenCOR_mem_leak/opencor_helper.py", line 46, in run
    mem = self.resource_module.getrusage(self.resource_module.RUSAGE_SELF).ru_maxrss
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'resource' has no attribute 'getrusage'
```
And, indeed, `import resource; dir(resource)` returns:
```
['RLIMIT_AS',
 'RLIMIT_CORE',
 'RLIMIT_CPU',
 'RLIMIT_DATA',
 'RLIMIT_FSIZE',
 'RLIMIT_MEMLOCK',
 'RLIMIT_MSGQUEUE',
 'RLIMIT_NICE',
 'RLIMIT_NOFILE',
 'RLIMIT_NPROC',
 'RLIMIT_OFILE',
 'RLIMIT_RSS',
 'RLIMIT_RTPRIO',
 'RLIMIT_RTTIME',
 'RLIMIT_SIGPENDING',
 'RLIMIT_STACK',
 'RLIM_INFINITY',
 'RUSAGE_CHILDREN',
 'RUSAGE_SELF',
 'RUSAGE_THREAD',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'error',
 'getpagesize',
 'getrlimit',
 'prlimit',
 'setrlimit',
 'struct_rusage']
```

**Comment by agarny** [comment]
Not sure why the `resource` module doesn't include `getrusage`, but that got me to look for another way to get memory usage using the [`psutil` module](https://pypi.org/project/psutil/), not least since it's properly cross-platform unlike the `resource` module.

Then, I came across [this page](https://fa.bianp.net/blog/2013/different-ways-to-get-memory-consumption-or-lessons-learned-from-memory_profiler/) which says that `orphaned arrays are liberated by the python interpreter, which is correctly seen by psutil but not by resource`, but that doesn't seem to be an issue here.

Anyway, the above is just for your record if you want people to be able to test things outside of Linux. :)

**Comment by agarny** [comment]
@FinbarArgus, your call to `simulation.clear_results()` does the correct thing. In other words, it should NOT call `pSimulation->data()->reset();`, not to mention that before calling `simulation.clear_results()` you call `simulation.reset(True)` which in turn calls `simulation->data()->reset()` (from C++; see [here](https://github.com/opencor/opencor/blob/fcc99737ef15e4eb776662f20f7b467da6fa6e77/src/plugins/support/SimulationSupport/src/simulationsupportpythonwrapper.cpp#L337-L342) and [here](https://github.com/opencor/opencor/blob/fcc99737ef15e4eb776662f20f7b467da6fa6e77/src/plugins/support/SimulationSupport/src/simulation.cpp#L2074-L2085)).

When it comes to your call `simulation.clear_results()`, it calls `SimulationResults::reset()` (from C++; see [here](https://github.com/opencor/opencor/blob/fcc99737ef15e4eb776662f20f7b467da6fa6e77/src/plugins/support/SimulationSupport/src/simulationsupportpythonwrapper.cpp#L346-L351) and [here](https://github.com/opencor/opencor/blob/fcc99737ef15e4eb776662f20f7b467da6fa6e77/src/plugins/support/SimulationSupport/src/simulation.cpp#L1006-L1016)), and we can see that it deletes and recreates the data store, which is what you would expect indeed.

FWIW, I originally tried your "fix", but didn't see any difference, hence my above conclusions as I digged a bit deeper. So, could the issue you are facing related to Python garbage collection? Just to check, I `import gc` and then called `gc.collect()` before every call to `mem = ...` and it looked a bit better, but not perfect.

So, next for me is to confirm that whatever gets allocated within a `Simulation` object actually gets deleted. Will report back...

**Comment by agarny** [comment]
Just for the record, I have put some traces with a counter to confirm that all the objects that get allocated within a `Simulation` object eventually get released. And it all works fine in OpenCOR itself, i.e. my counter increases to a given value and then goes back to zero. However, in the Python bindings, I can see some objects that don't get released. FWIW, it doesn't matter whether `result = sim.simulation.results().states()['heart/q_lv'].values()` is commented out or not, there is still a memory leak.

So, I am checking the Python bindings, which is a bit tedious, but I will get there! (Thank god, this kind of issue cannot exist in libOpenCOR!)

**Comment by agarny** [comment]
Ok, contrary to what I mentioned in my previous message, there were no more objects that could be released... as long as, in the Python script, we call `sim.close_simulation()` (which wasn't the case in `run_simple.py`). If we do that then everything gets released as expected.

**Bottom line:** there are NO memory leaks in the OpenCOR's Python bindings, but... memory is allocated when retrieving some values (as a  NumPy array; e.g. `result = sim.simulation.results().states()['heart/q_lv'].values()`) and it only gets released once a Python script ends. So, in cases where we need to retrieve memory as soon as possible, we can now call `release_values()` (e.g., `sim.simulation.results().states()['heart/q_lv'].release_values(result)`).

**Comment by FinbarArgus** [comment]
Hi Alan, 

Thank you for all of this! Is there any chance you could add a sim.simulation.release_all_values() that releases all states and algebraic variables? So that it can be simply called with/after sim.simulation.clear_results() to reset all memory.

**Comment by agarny** [comment]
Hi @FinbarArgus, I believe there might some technical isssues, but by all means do create a GitHub issue for it and I will look into it in more details.
